all: install

install: installer.sh setup

installer.sh:
	curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh

setup:
	sh ./installer.sh ~/dotfiles/_vim/dein
